 language: node_js
 node_js:
   - "0.10"

 before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  
 install: npm install
 
 notifications:
  email:
    recipients:
      - info@digitalfondue.ch
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always